pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "MIRA-IDV3"

// تسجيل الموديولات الخمسة
include ':app'
include ':mira-core'
include ':mira-rfid'
include ':mira-inventory'
include ':mira-ui'
