plugins {
    id 'com.android.library'
}

android {
    namespace 'com.mira.rfid'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    // 🛑 استبعاد كافة الـ Fragments المعطوبة المتبقية من SDK أجهزة RFID القديمة
    sourceSets {
        main {
            java {
                // المجمعة الأولى
                exclude '**/UHFRadarLocationFragment.java'
                exclude '**/UHFKillFragment.java'
                exclude '**/UHFUpgradeFragment.java'
                exclude '**/ProtectedModeAndShortRangeModeFragment.java'
                exclude '**/UHFTagLitFragment.java'
                exclude '**/UHFTagFlashFragment.java'
                exclude '**/UHFLockFragment.java'
                
                // المجمعة الثانية (التي ظهرت في الـ Build الأخير)
                exclude '**/UHFSetFragment.java'
                exclude '**/UHFLocationFragment.java'
                exclude '**/UHFReadWriteFragment.java'
                exclude '**/UHFReadTagFragment.java'
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // ربط موديولات الـ UI والـ Core لكي يراها mira-rfid
    implementation project(':mira-core')
    implementation project(':mira-ui')

    // قراءة ملفات Jar و Aar الخاصة بأجهزة RSCJA / UHF داخل مجلد libs الخاص بـ mira-rfid
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    // شبكات ومكتبات
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
